import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { DevCycleClientsideProvider } from "@devcycle/nextjs-sdk";
// import the getClientContext method from your shared DevCycle file
import { getClientContext } from "./devcycle";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DevCycleClientsideProvider context={getClientContext()}>
          {children}
        </DevCycleClientsideProvider>
      </body>
    </html>
  );
}
